### PR TITLE
Events 

### PR DESCRIPTION
**Pull request by flyhard**
- Merged the current master
- Applied standard formatting
- Added tests for events
- added documentation for the events

### CODE REVIEW

**Comment by takumakanari** [comment]
It's better to rebase `tkmgo:events` with master first,, I think.

**Comment by takumakanari** [comment]
Also I think it's better to merge #1 to master first.

**Comment by flyhard** [comment]
Rebased on top of your rebase

**Comment by flyhard** [comment]
As you might have seen, this is a PR to update the events branch which then leads to #1 - so in fact iti is an update to #1

**Comment by takumakanari** [comment]
Thank you.

**Pull request merged**
